### ISSUE TITLE
kippo-graph

### ISSUE THREAD

**Issue by necrose99** [hashashin/gentoo-vaca-overlay#1]
https://github.com/ikoniaris/kippo-graph

might be worth adding..

**Comment by hashashin** [comment]
Thanks for the suggestion, I'll take a look :+1:

**Comment by hashashin** [comment]
added via a3920a8 and f95e592 lasted release 1.5. Let me know if you want a -9999 (master) ebuild too.

Salud.

**Comment by necrose99** [comment]
can if you like , i have a template for some of the others https://github.com/Sabayon-Labs/spike-community-overlay/tree/master/net-analyzer/kojoney (https://github.com/madirish/kojoney2  closes open gentoo bug) 
mainly trying to fix up main repo, 
https://github.com/Spike-Pentesting/spike-overlay  #spike-pentesting  #spike-pentesting-dev 
also a template for bad samba etc some reson repoman is being a pest i wish i had a better manifest gen script.  mudler will likey apeciate any security packages that you push , and you can watch them build in irc in the dev channel.
